### ISSUE TITLE
Merkmalskenntnis

### ISSUE THREAD

**Issue by Bellistor** [MarkusBauer/helden-software-loader#11]
Hallo,

erst einmal herzlichen Dank für die schöne Erweiterung!

Unser SL hat ein spezielles Merkmal definiert (für den silbernen Schlangenreif in den 7G) das ich gerne im Tool abbilden würde.
"Alle Elementar-Zauber 1 Spalte günstiger steigern bis auf Elementar(Eis)"
Es lässt sich über einen Metagegenstand im Inventar realisieren:
- Elementar 1 Spalte günstiger
- Elementar (Eis) 1 Spalte teuerer

Aber es verbraucht dann keinen der "Merkmals-Slots"
> Leiteigenschaft (KL oder IN; Seite 12) 13 für die
> Kenntnis eines zweiten Merkmals, Leiteigenschaft 15 für die Kenntnis von drei Merkmalen, Leiteigenschaft 16 für 4 Merkmale, 17
> für 5, 18 für 6 usw.
WdH p288

In der Readme wird bei Sonderfertigkeiten der Typ "Magisch: Merkmalskenntnis" gelistet.
```JSON
{
    "zauber": [],
    "sonderfertigkeiten": [
        {
            "name": "Merkmalskenntnis: Elementar (Geode, spezial)",
            "kategorie": "Magisch: Merkmalskenntnis",
            "kosten": 0
        }
    ]
}
```
**FRAGE**: Kann man dem Dict noch weitere Keys hinzufügen um die Auswirkungen zu definieren?

Beste Grüße
Bellistor

Mein JSON File ... mit .txt Erweiterung weil GitHub .json nicht zulässt:

[erweiterungen.json.txt](https://github.com/MarkusBauer/helden-software-loader/files/9998119/erweiterungen.json.txt)

**Comment by Bellistor** [comment]
Ok, hat sich erledigt. Steht ja alles in den Examples. Sry

**Comment by MarkusBauer** [comment]
Hallo, 
weitere Effekte zu einer Sonderfertigkeit hinzufügen ist nicht möglich. Neue Merkmals-Sonderfertigkeiten sollten allerdings einen Merkmals-Slot belegen und (neue, eigene) Zauber mit diesem Merkmal verbilligen.
In deinem Fall könnte man bspw. eine "leere" Sonderfertigkeit nutzen und die Effekte mit den genannten Meta-Gegenständen realisieren. 

Die Liste im Format `"zauber": {"Armatrutz": 7, ...}` ist nur für Repräsentationen definiert (um die Verbreitung bestehender Zauber anzugeben. Eine Liste mit neuen Zaubern kann unabhängig von Repräsentationen oder Sonderfertigkeiten angegeben werden - neue Zauber können dabei eigene Repräsentationen und Merkmale direkt nutzen.

Bestehende Zauber lassen sich nicht überschreiben - das wäre auch sehr kontraproduktiv, da alle Helden auf den selben Zauber-Pool zurückgreifen. Bei Bedarf könnte man neue Varianten der Zauber mit geänderten Merkmalen anlegen, wie das die Helden-Software beispielsweise schon mit den Agrimoth-Varianten aus "Stätten okkulter Geheimnisse" macht ("Armatrutz (Agm)" und co.).

Lässt sich dein Fall damit realisieren?

**Comment by Bellistor** [comment]
> In deinem Fall könnte man bspw. eine "leere" Sonderfertigkeit nutzen und die Effekte mit den genannten Meta-Gegenständen realisieren.

Ja, das mache ich jetzt. Eine Merkmalskenntnis definiert und über Editor hinzugefügt. Dazu ein Metagegenstand mit `Elementar` 1 Spalte billiger und `Elementar(Eis)` 1 Spalte teurer.

Die Zauber neu anlegen... das habe ich befürchtet und Nein, das ist mir zu viel Arbeit ;-)

Danke für die Antwort!
Gute Arbeit, guten Loot und hoffentlich immer noch viel Spaß mit DSA!

//Bellistor
