### ISSUE TITLE
Bedingungen

### ISSUE THREAD

**Issue by Dragon7O2** [MarkusBauer/helden-software-loader#12]
Hallo,
erst einmal super Plugin!

Wäre es möglich als Bedingung etwas anzugeben was der Held nicht Beherrschen darf? Ein grobes Beispiel wenn der Held eine bestimmte SF beherrscht dann darf er eine andere nicht anwählen.

**Comment by MarkusBauer** [comment]
Hallo, 
ja, das war relativ einfach möglich. Die neue Version 1.7 kann das: https://github.com/MarkusBauer/helden-software-loader/releases/tag/v1.7

In der Konfiguration wird dazu ein `"not": true` an die Bedingung geschrieben, zum Beispiel so:
```json
{"type": "SF", "name": "Blutmagie", "not": true}  // Darf nicht die Sonderfertigkeit Blutmagie haben
```
