### ISSUE TITLE
Bedingungen und neue Version

### ISSUE THREAD

**Issue by Dragon7O2** [MarkusBauer/helden-software-loader#13]
Hallo noch einmal,
danke noch einmal für die schnelle Rückmeldung und für das schnelle Update. Das ganze klappt sehr gut mit Sonderfertigkeiten die schon in der Heldensoftware vorhanden sind. Wenn ich nun aber bei zwei eigenen Sonderfertigkeiten zur Bedingung mache dass man nicht die jeweils andere besitzen darf dann funktioniert das ganze leider nicht weil das Programm anscheinend denkt dass die untere Sonderfertigkeit nicht existiert. Wäre es möglich so etwas wie ich in dem Beispiel unten habe hin zu bekommen?

Man sollte sich quasi aussuchen welche man haben möchte.

Beispiel :

{
    "sonderfertigkeiten": [
	   {
            "name": "Fokus der Schattenwelt", "kosten":  100, "kategorie":  "Geweiht",
			"bedingungen": [{"type": "Sonderfertigkeit", "name": "Liturgiekenntnis (Boron)"}
			{"type": "SF", "name": "Hammer der Furcht", "not": true}],
        },
        {
            "name": "Hammer der Furcht", "kosten":  100, "kategorie":  "Geweiht",
            "bedingungen": [{"type": "Sonderfertigkeit", "name": "Liturgiekenntnis (Boron"}
			{"type": "SF", "name": "Fokus der Schattenwelt", "not": true}],			
        },				
    ]
}

**Comment by MarkusBauer** [comment]
Hallo, 
guter Punkt. Bisher ging das nur mit bereits geladenen Sonderfertigkeiten. 
Mit [Version 1.7.1](https://github.com/MarkusBauer/helden-software-loader/releases/tag/v1.7.1) sollten jetzt auch alle eigenen Sonderfertigkeiten in Bedingungen funktionieren, damit sollte auch das Beispiel so funktionieren.

Viele Grüße
