### ISSUE TITLE
Eigene Repräsentationen

### ISSUE THREAD

**Issue by MarkusBauer** [MarkusBauer/helden-software-loader#4]
Idee aus dem dsaforum: Eigene Repräsentationen, inkl. der notwendigen SF. 

Use Cases: Halbzauberische Alchimisten, Dunkelelfische Repräsentation, Feeische Repräsentation

**Comment by markusschaber** [comment]
Oder die kleindrachische Repräsentation aus der Spielhilfe von Desiderius Findeisen: https://dsanews.de/der-kleindrache-als-spielerheld/

**Comment by MarkusBauer** [comment]
Eigene Sonderfertigkeiten und Repräsentationen sind in der neuen [Vorab-Version 1.3-beta](https://github.com/MarkusBauer/helden-software-loader/releases/tag/v1.3-beta) möglich. Bitte um Feedback!

Falls jemand bereits Hausregel-Sammlungen (wie die oben verlinkte) konfiguriert hat würde ich mich über die Datei sehr freuen.
