### ISSUE TITLE
Unterstützung hslocal Modus

### ISSUE THREAD

**Issue by Derevar** [MarkusBauer/helden-software-loader#5]
Moin,
anscheinend unterstützt der loader leider wohl nicht die `-hslocal` (und `-ep`) Flag. Wäre es möglich das bitte hinzuzufügen? Ich synchronisiere den Helden-Software Ordner mit Seafile, das wäre recht praktisch.

Die Flag für die Helden-Software unterstützt einen portable Modus. Meine helden.zip.hld ist nicht unter `%homepath%\helden` sondern liegt relativ zur Helden.jar:

![grafik](https://user-images.githubusercontent.com/657768/82160618-fc156b80-9896-11ea-9b84-a49f7e384dc8.png)

Nach dem Benutzen der Flag ist die Option übrigens auch in der `.heldEinstellungen4_1.xml` enthalten:
![grafik](https://user-images.githubusercontent.com/657768/82160791-14d25100-9898-11ea-8e4d-72b5d2e64f95.png)

Damit der loader die `erweiterung.json` erkennt muss sie aber im homepath-Verzeichnis liegen.

Es müsste wohl diese Stelle hier angepasst werden:
https://github.com/MarkusBauer/helden-software-loader/blob/master/src/main/java/de/mb/heldensoftware/customentries/CustomEntryLoader.java#L212

Informationen zur Flag gibt es hier:
http://wiki.helden-software.de/wiki/FAQ

**Comment by MarkusBauer** [comment]
Das Plugin sollte eigentlich schon Erweiterungen finden, die im selben Ordner wie die `helden.jar` liegen. Wo liegen denn im gezeigten Beispiel die beiden Jar-Dateien?

**Comment by Derevar** [comment]
Ah... ja das funktioniert auch. Dass die Datei auch neben der *.jar liegen kann steht leider nicht in der README.md und anscheinend war ich zu blind das in der `loadFiles()` Methode 5 Zeilen drüber zu sehen.

Die *.jar Dateien liegen ein Verzeichnis drüber. Aber funktioniert jetzt quasi so wie gewünscht.
Danke für die Hilfe.

**Comment by MarkusBauer** [comment]
Danke, ich hab das in der Readme ergänzt. Außerdem findet das Plugin mit [der neusten Version v1.3.1](https://github.com/MarkusBauer/helden-software-loader/releases/tag/v1.3.1) den `helden`-Ordner auch dann, wenn `-hslocal` verwendet wird.
