### ISSUE TITLE
Vergünstigungen auf eigenerstellte SFs bei Vorteil Akademische Ausbildung

### ISSUE THREAD

**Issue by tinoginelli** [MarkusBauer/helden-software-loader#6]
Hallo ich habe gestern mal dein Plug-in ausgetestet und mir sind einige Fehler aufgefallen.

z.B. Bei eigenen SFs die man einer Magischen Kategorie hinzufügt (bsp.: Objektrituale) gibt es automatisch eine Vergünstigung wenn der Spielerheld ein Magier ist und den Vorteil Akademische Ausbildung (Magier) besitzt. Diese verbilligt alle Gildenmagier SFs aber keine von fremden Repräsentationen. Bei uns sollen die SFs eben kristallomantischer Natur sein. 
Als Workaround habe ich sie jetzt der Kategorie Allgemein hinzugefügt, ist natürlich nicht schön.
Da man bei den SFs keine Repräsentation oder Merkmale in der json angeben kann, nehme ich an, dass die Heldensoftware default von der Gildenmagischen Rep ausgeht.
Evtl. lässt sich da was machen, ggf. die Repräsentation mit hinzufügen bei den SFs oder gar merkmale.

Liebe grüße und danke für euer tolles Plugin :)

**Comment by MarkusBauer** [comment]
Hallo, 
mit der neusten Version lässt sich das Problem beheben. 

Für die Helden-Software fallen alle Sonderfertigkeiten unter die "Akademische Ausbildung", die
1. aus einer der magischen Kategorien stammen (inkl. Objektritualen, Elfenliedern etc)
2. als Vorbedingung die Gildenmagische Repräsentation/Ritualkenntnis haben  ODER  keine _andere_ Ritualkenntnis als Vorbedingung haben. 

In der Neuen Version lässt sich das lösen, indem man eine Bedingung auf die korrekte Ritualkenntnis zur Sonderfertigkeit hinzufügt. Das könnte etwa so aussehen:

```json
{
    "sonderfertigkeiten": [
        {"name": "Kristall-Stab", "kosten":  200, "kategorie":  "Objektritual", "bedingungen": [
            {"type": "Sonderfertigkeit", "name": "Ritualkenntnis: Kristallomantie"}
        ]}
    ]
}
```

Viele Grüße, und danke für's melden!
