### ISSUE TITLE
Speicherort für Erweiterungen ignoriert via helden.jar geänderte Speicherpfade 

### ISSUE THREAD

**Issue by magicalmarisa** [MarkusBauer/helden-software-loader#7]
Die Helden-Software erlaubt es, unter _Einstellungen_ > _Speicherpfade ändern_ den Speicherort (u.a.) der Datei `helden.zip.hld` anzupassen.

Entgegen der Aussage im Readme werden Erweiterungen aber immer noch im Ordner `~/helden/` gesucht.
> Diese Datei kommt ins gleiche Verzeichnis wie eure helden.zip.hld

Es wäre schön, wenn das Plugin alternative Speicherorte unterstützte. Ansonsten sollte zumindest die Dokumentantion angepasst werden.

Alternative Speicherpfade machen es einfach, seine Helden über die Cloud zu sychronisieren. Ich nutze beispielsweise die Helden-Software auf drei verschiedenen Computern mit den Speicherpfaden `/home/marisa/Nextcloud/helden/`, `/Users/marisa/Nextcloud/helden` und `C:\Users\Marisa\Nextcloud\helden\`.

**Comment by MarkusBauer** [comment]
Hallo, 
danke für die Meldung.
Diese Version sollte das Problem beheben. Damit werden die gesetzten Einstellungen bereits vorm Start der Helden-Software geladen. [helden-software-loader-1.4.1-release.zip](https://github.com/MarkusBauer/helden-software-loader/files/7204373/helden-software-loader-1.4.1-release.zip)

Funktioniert damit alles wie gewünscht? Dann würde ich das noch als neues Release hochladen.

Viele Grüße
Markus

**Comment by magicalmarisa** [comment]
Ich habe es gerade ausprobiert: in meiner Kofiguration funktioniert es (zumindest unter macOS und Linux, auf den Windows-Rechner habe ich gerade keinen Zugriff).

Dankeschön 😊

**Comment by MarkusBauer** [comment]
Danke, die neue Version ist hochgeladen.
