### ISSUE TITLE
Ist es möglich, die Kleidung im Ausrüstungsbogen zu ändern?

### ISSUE THREAD

**Issue by Tykato** [MarkusBauer/helden-software-loader#8]
Hi, danke erstmal für das grandiose Plugin!

Zu meiner Frage: In der Druckvorschau gibt es den "AusrüstungsbogenN", welcher oben links 'Kleidung' aufführt. Leider finde ich keine Möglichkeit, um hier in der Helden-Software Eintragungen vorzunehmen. Ist es möglich, das per Plugin nachzuliefern?

Danke und Gruß

**Comment by MarkusBauer** [comment]
Hi, 
leider sehe ich keine einfache Möglichkeit, Eintragungen zum Heldenbogen hinzuzufügen. 
Gruß
Markus
