### ISSUE TITLE
Liturgien

### ISSUE THREAD

**Issue by Dr4gon7O2** [MarkusBauer/helden-software-loader#9]
Ich bin auf das Problem gestoßen, dass wen man eine neue Liturgiekenntnis hinzu fügt und man ihr ermöglicht bereits existierende Liturgien nutzen zu können, alle anderen Geweihten Professionen dann diese nicht mehr kaufen können oder sie ruhend sind. Also löscht die neue Vorbedingung bereits existierende von der Heldensoftware.

**Comment by MarkusBauer** [comment]
Hallo, 
danke für den Hinweis. Wie konfigurierst du denn die Liturgiekenntnis und die zugehörigen Liturgien? Ist es möglich, deine json-Datei hier zu posten?

**Comment by Dr4gon7O2** [comment]
Danke für die schnelle Rückmeldung.
Da es mir nicht müglich ist die json Datei hier zo posten mache ich es per Dropbox.
https://www.dropbox.com/s/gyhlwy6rc9a3t7i/erweiterungen.json?dl=0
Ich hoffe es reicht als Beispiel.

**Comment by Dr4gon7O2** [comment]
Danke für die schnelle Rückmeldung.
Da es mir nicht möglich ist die json Datei hier zo posten mache ich es per Dropbox.
https://www.dropbox.com/s/gyhlwy6rc9a3t7i/erweiterungen.json?dl=0
Ich hoffe es reicht als Beispiel.

**Comment by Dr4gon7O2** [comment]
{
    "sonderfertigkeiten": [
        {"name": "Liturgiekenntnis (Marbo)", "kosten":  0, "kategorie":  "Geweiht"},
 
         {"name": "Liturgie: Weisheitssegen", "kosten":  50, "kategorie":  "Geweiht: Liturgie", "bedingungen": [
            {"type": "Sonderfertigkeit", "name": "Liturgiekenntnis (Marbo)"},  
        ]}
    ],
}

**Comment by Dr4gon7O2** [comment]
Ich habe auch daran gedacht die Liturgien die Sonderfertigkeit Karmalqueste als Vorraussetzung haben zu lassen.
Das funktioniert aber leider nur Regelkonform mit den Grad 1 Segnungen.

**Comment by Dr4gon7O2** [comment]
[erweiterungen.zip](https://github.com/MarkusBauer/helden-software-loader/files/7574838/erweiterungen.zip) Hier nochmal die komplette json mit allem was ich hinzugefügt habe.

**Comment by MarkusBauer** [comment]
Was hier passiert ist: Mit der Config wurden neue Liturgien angelegt, die die Alten vollständig überschreiben. 
Das heißt auch andere Geweihte verweisen dann auf die neuen Liturgien, die ihnen natürlich nicht zugänglich sind. 
Bisher war die Konfiguration der Bedingungen nicht fein genug möglich, um damit sinnvolle Liturgie-Bedingungen zu bauen.

Außerdem ist mir aufgefallen, dass der Heldengenerator Liturgien intern anders als andere Sonderfertigkeiten behandelt (bspw. wird der Grad der Liturgie mitgespeichert) - was dieses Plugin bisher ignoriert hat.

Mit der [neuen Version 1.5](https://github.com/MarkusBauer/helden-software-loader/releases/tag/v1.5) sollte die Probleme lösen. Konkret ändert sich für diesen Fall:

- Die Liturgiekenntnis bekommt jetzt eine Liste mit bereits existierenden Liturgien, deren Bedingung gepatcht wird. Diese sind dann zusätzlich für Geweihte mit der neuen Liturgiekenntnis zugänglich.
  ```
  {
      "name": "Liturgiekenntnis (Marbo)", "kosten":  0, "kategorie":  "Geweiht",
      // nur zugänglich, wenn Vorteil "Geweiht" etc bereits vorhanden
      "bedingungen": [{"type": "MagieLevel", "name": "Geweihter"}],
      // diese bereits existierenden Liturgien sind zugänglich
      "liturgien": ["Schutzsegen", "Grabsegen", "Weisheitssegen"]
  }
  ```
- Neue Liturgien werden jetzt mit `grad` und `liturgiekenntnis` angegeben, die dann Kosten und Bedingungen setzt:
  ```
  {
      "name": "Liturgie: Vampirische Kräfte", "kategorie": "Liturgie", "grad": 2,
      "liturgiekenntnis": ["Marbo"]
  }
  ```

Damit sollten sich die Marbo-Geweihten ohne Probleme (und mit deutlich weniger Code) realisieren lassen.
Ich hatte das mit [diesem Beispielcode](https://github.com/MarkusBauer/helden-software-loader/blob/master/README.md#neue-liturgien-und-geweihte) getestet.
Falls noch was nicht funktioniert gerne nochmal melden.


PS: Was war eigentlich die Idee hinter diesem Teil? Warum hat die Sonderfertigkeit sich selbst zur Bedingung?

> ```
> {"name": "Liturgiekenntnis (Marbo)", "kosten":  0, "kategorie":  "Geweiht", "bedingungen": [
>     {"type": "Sonderfertigkeit", "name": "Liturgiekenntnis (Marbo)"},
> ]}
> ```

**Comment by Dr4gon7O2** [comment]
Hallo,
1. Vielen Dank für die tollen und vorallem auch schnellen updates.
2. Zu dem sich selbst als Bedingung haben hatte es auf sich dass ich in der Software eine eingene Profession gebaut hatte und somit es nicht nötig war sich die Liturgiekenntnis kaufen zu können, was ja andere Geweihte eh nicht sollten.
Daher habe ich es als einfache Lösung gesehen die Liturgie einfach sich selbst als Bedingung zu haben, somit war sie nicht mehr normal anwählbar.

**Comment by Dr4gon7O2** [comment]
Hallo,

1.Vielen Dank für die tollen und vorallem auch schnellen updates.
2.Zu dem sich selbst als Bedingung haben hatte es auf sich dass ich in der Software eine eingene Profession gebaut hatte und somit es nicht nötig war sich die Liturgiekenntnis kaufen zu können, was ja andere Geweihte eh nicht sollten.
Daher habe ich es als einfache Lösung gesehen die Liturgie einfach sich selbst als Bedingung zu haben, somit war sie nicht mehr normal anwählbar.
